Fix Datetime issue
hashtopolis/web-ui pull request #16
Opened 2023-08-31 10:08 UTC by xbenyx

Added below the Config setting a second date with instructions that one affects the old ui an another the new ui. Old ui has form control input text and New UI has select option.

2023-09-01 13:03 UTC, zyronix requested changes
Please implement feedback

2023-09-01 13:03 UTC, zyronix commented on src/app/account/settings/settings.component.ts
Call the variable something like `localtimefmt`. I am pretty sure that this workaround will be inside the code for a longer time.

2023-09-01 13:03 UTC, zyronix commented on src/app/account/settings/settings.component.ts
This apply to all files

2023-09-01 13:03 UTC, zyronix commented on src/app/config/server/server.component.html
> +              <form [formGroup]="temptimeForm">
I would not place this in the server settings place. Create a new settings for web-ui sittings under the user drop down:
![image](https://github.com/hashtopolis/web-ui/assets/4386076/3362fe45-6d77-4165-a948-58455aa46ca1)

Rename settings to: Account Settings
Add new one call this UI Settings

2023-09-01 13:03 UTC, zyronix commented on src/app/core/_services/shared/storage.service.ts
> +    if(Date.now() > timestamp + expires){
Does this work? For easyier reading make this:
`(Date.now() > (timestamp + expires))`

2023-09-01 13:03 UTC, zyronix commented on src/app/core/_services/shared/storage.service.ts
> +        if(name == 'temptime'){  //Once dropping old UI change this for  timefmt
Remove comment

2023-09-01 13:03 UTC, zyronix commented on src/app/core/_services/shared/storage.service.ts
In this file there is still the function:

```
  public updateDate(val){
    const keyn = 'timefmt';
    const params = {'filter=item': keyn};
    this.gs.getAll(SERV.CONFIGS,params).subscribe((result)=>{
      const indexUpdate = result.values.find(obj => obj.item === keyn).configId;
      const arr = {'item': keyn, 'value':  val};
      this.gs.update(SERV.CONFIGS,indexUpdate, arr).subscribe((result)=>{ }) })
  }
```

When you for example switch to the full width mode and I guess also when the settings expire, this function is still called. Please completly remove this function.

2023-09-01 13:03 UTC, zyronix commented on src/app/tasks/edit-tasks/edit-tasks.component.ts
> +  console.log(result)
Remove

2023-09-01 13:03 UTC, zyronix commented on src/app/tasks/edit-tasks/edit-tasks.component.ts
> +          start: 70,
Why are there changes regarding speed inside this pull request?

2023-09-01 19:19 UTC, xbenyx commented on src/app/account/settings/settings.component.ts
Im saving the format using a cookie with expiry one year.  The name localtimefmt is being used. With the new pipe I can easily manage any future change in the date, also reducing the code.

2023-09-01 19:20 UTC, xbenyx commented on src/app/config/server/server.component.html
> +              <form [formGroup]="temptimeForm">
New section has been created with the instructions above.

![image](https://github.com/hashtopolis/web-ui/assets/13848557/f8d14f52-d42f-4254-8858-e870e55c596a)

2023-09-01 19:21 UTC, xbenyx commented on src/app/core/_services/shared/storage.service.ts
> +        if(name == 'temptime'){  //Once dropping old UI change this for  timefmt
Removed since now we are using the pipe

2023-09-01 19:24 UTC, xbenyx commented on src/app/core/_services/shared/storage.service.ts
N/A  - Also tested with full width and logout and new date is persistent. Even if the date is modified from the cookies this will check the right format and swap the format.

2023-09-01 19:26 UTC, xbenyx commented on src/app/core/_services/shared/storage.service.ts
> +    if(Date.now() > timestamp + expires){
No, I changed it.

2023-09-05 13:36 UTC, zyronix approved these changes
I don't understand why this was not placed into localstorage but is now places in a cookie. As this is not something that should be sent the the server. Also with the introduction of the datapipe it would have been possible to implement converting this using the current dateformat stored in the config. As that wuld have been a perfect place to do the convertation of the dateformat to javascript date.

Also I removed the code that was still possible to trigger where updates were sent to the config endpoint.

I also merged the current master as there was a conflict.

2023-09-05 13:37 UTC, merged

2023-09-06 07:24 UTC, xbenyx commented
_"I don't understand why this was not placed into localstorage but is now places in a cookie."_, just add it as cookie as the variables in local storage have a short expiry date. As this a temp solution, i moved to cookies. 

_"Also with the introduction of the datapipe it would have been possible to implement converting this using the current dateformat stored in the config."_, well good point......actually it could be a cleanest solution.